


# this is a post example
POST http://localhost/training/ProjectWeek2/Login.php HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user" 

hsingh1@pipingrock.com 
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="pass"; 

Assignment1


